### ISSUE TITLE
Can't scroll when signup modal is open

### ISSUE THREAD

**Issue by kevgathuku** [andela-kndungu/document-ms-frontend#21]
It was my initial perception that I should still be able to scroll when the signup modal is open, especially since the signup is positioned way down in the page
I was trying to scroll to position it more centrally but I can't. 
Also, shouldn't the signup modal also have the social buttons?
<img width="1277" alt="screen shot 2016-08-30 at 10 46 36 am" src="https://cloud.githubusercontent.com/assets/3721994/18080678/280868c6-6e9f-11e6-9764-1dc8050ed9a5.png">

**Comment by kndungu** [comment]
@kevgathuku since i'm using material-ui's dialog to implement the modal I have to rely on it's default behaviour which is to prevent any interaction with the background.

On the social buttons: Technically you are using Google or GitHub to log in not sign up. A bit of semantics. All in all I think it looks cleaner with its current implementation.
