### ISSUE TITLE
Cannot copy another user's document content when logged in

### ISSUE THREAD

**Issue by kevgathuku** [andela-kndungu/document-ms-frontend#32]
I've noticed that when I am logged in and try to copy the contents of another user's document, it does not work. Nothing is copied to the clipboard.

However, when I am logged in, I can copy my own documents' content to the clipboard and I can also copy any content from any user when I am not logged in.

Is this intended behavior?

**Comment by kndungu** [comment]
No it is not, I was just as surprised as you were.

I'm using [draft.js](https://facebook.github.io/draft-js/) to display and edit the title and content when a user is logged in. Users can however only edit their documents, a side effect I suppose is that a user can only copy their own documents.

Unintended but I have to admit, it's a pretty cool feature to have, fights plagiarism :'D

I'm not going to solve this one, the bug is now officially a feature :-D

**Comment by kevgathuku** [comment]
It is an interesting bug, but it doesn't really fight plagiarism as I could just logout and copy another person's document. 
I'll however look into whether it has been reported before in the draft.js issue tracker.
